### ISSUE TITLE
Support for LanguageClient

### ISSUE THREAD

**Issue by erlanger** [jamesnvc/lsp_server#2]
I tried to use it  in neovim with [LanguageClient](https://github.com/autozimu/LanguageClient-neovim), but LanguageClient does not support incremental mode. It can only handle the whole file. I don't think they will ever add support for incremental mode.

Is there a chance you will support LanguageClient? It is easier to support and fix things in prolog than in rust (LanguageClient is written mostly in rust and viml).

**Comment by jamesnvc** [comment]
Sure, I'll have a look

**Comment by jamesnvc** [comment]
I installed LanguageClient with a clean nvim configuration & I'm able to see hover working, but it looks the go to definition & find usages isn't working. I will try to figure out why.

**Comment by jamesnvc** [comment]
Just released v1.2.0 which seems to be working in Neovim with LanguageClient for me. Let me know if you have any issues with it!

**Comment by erlanger** [comment]
Thanks!! I just tried it, and it fails to start with the following error:
[LC] LanguageClient: failed to register as NCM source: invalid type: boolean `false`, expected struct CodeLensOptions

I am using 

    Plug 'ncm2/ncm2'

for completions.

Here are the logs:

[ls1.log](https://github.com/jamesnvc/lsp_server/files/3487721/ls1.log)
[lc1.log](https://github.com/jamesnvc/lsp_server/files/3487723/lc1.log)

You can see that it is not handling the textDocument/didChange in lc1.log above.

**Comment by jamesnvc** [comment]
Ah okay, so this is for a completion framework? Right now, I only have documentSymbols, hover, defintition, and references implemented. I can work on adding completion as well, but probably not until the end of August.

**Comment by jamesnvc** [comment]
Would you be able to post a minimal init.vim for testing?

**Comment by jamesnvc** [comment]
Oh, I see; it just sends errors merely trying to load with the plugin enabled. I will push a fix to address that.

**Comment by jamesnvc** [comment]
Released v1.2.1 that, while completion isn't implemented, doesn't give errors on launch.

**Comment by erlanger** [comment]
I updated the repo (1.2.1 is not at the main website yet) and it starts now. The  functions that are working are 
* LanguageClient_textDocument_documentSymbol(): which actually just lists the symbols, the actual docs are shown by hover.
* LanguageClient_textDocument_hover(): which shows the documentation on a window (nice!)

**Comment by erlanger** [comment]
BTW, you are going to beat the record on responding to issues! Thank you so much!

**Comment by jamesnvc** [comment]
I was able to see go to definition & go to references working for me; are they working for you?

**Comment by erlanger** [comment]
Yes, both are working great!
